algoritmo "semnome"
// Função :
// Autor :
// Data : 09/03/2018
// Seção de Declarações 
var
x : vetor[1..20] de inteiro
j,i : inteiro
inicio
// Seção de Comandos 
para i de 1 ate 20 faca
escreval("==================")
escreva("Informe um numero: ")
leia(x[i])
escreval("==================")
escreval("A tabuada do numero")
escreval("===================")
para j de 1 ate x[i] faca
escreval(x[i] * j)
escreval()
fimpara
fimpara

fimalgoritmo
