algoritmo "Exercicio 5"
// Função :
// Autor :
// Data : 26/04/2018
// Seção de Declarações 
var
m : vetor[1..3,1..4] de inteiro
i,j: inteiro
inicio
// Seção de Comandos
para i de 1 ate 3 faca
     para j de 1 ate 4 faca
          leia(m[i,j])
     fimpara
fimpara
para i de 1 ate 3 faca
     para j de 1 ate 4 faca
          escreva(m[i,j])
     fimpara
     escreval()
fimpara
fimalgoritmo
